spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-conversion
  zipkin:
    base-url: http://128.199.218.101:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
server:
  port: 8100
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
